modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/lumien231/QuickLeafDecay"
displayURL="https://minecraft.curseforge.com/projects/quick-leaf-decay"

authors="Lumien" #optional

[[mods]]
    modId="quickleafdecay"
    version="${file.jarVersion}"
    displayName="Quick Leaf Decay"
    description='''
Makes leaves decay faster
'''
[[dependencies.quickleafdecay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.quickleafdecay]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
